REPORTER = spec
TEST_DIR = ./tests/server
TEST = "./node_modules/.bin/mocha" $(TEST_DIR) --reporter $(REPORTER) \
       	--color --verbose --check-leaks --slow 75
test:
	$(TEST)
test-w:
	$(TEST) --watch

.PHONY: test test-w